services:
  - type: web
    name: storybyimage
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn imagedescriber.wsgi:application"
    build:
      runtime: python 3.11
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: imagedescriber.settings
      - key: DEBUG
        value: "False"
